const ReservationsActions = {
    CHANGE_VALUE: "CHANGE_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_VALUE_FORM",
    RELOAD_LIST: "RELOAD_LIST",
    RESET_FORM: "RESET_FORM",
    CHANGE_ALL_VALUE_FORM: "CHANGE_ALL_VALUE_FORM",
    LOADED_RESERVATION_LIST: "LOADED_RESERVATION_LIST",
}

export default ReservationsActions