const HOME_ACTIONS = {
    CHANGE_VALUE: "CHANGE_VALUE",
    CHANGE_VALUE_RESERVE_BAR: "CHANGE_VALUE_RESERVE_BAR",
    GET_OCCUPIED_DATES: "GET_OCCUPIED_DATES",
    GET_ROOMS: "GET_ROOMS",
    GET_OFFERS: "GET_OFFERS",
    SET_LOADING: "SET_LOADING",
}

export default HOME_ACTIONS
