const EmployeeActions = {
    LOADED_EMPLOYEES_LIST: "LOADED_EMPLOYEES_LIST",
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    CHANGE_VALUE: "CHANGE_EMPLOYEE_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_EMPLOYEE_FORM_VALUE",
    SET_SEARCH_TERM: "SET_EMPLOYEES_SEARCH_TERM",
    CLEAN_FORM_DATA: "CLEAN_FORM_DATA",
    SET_CURRENT_EMPLOYEE: "SET_CURRENT_EMPLOYEE",
    RELOAD_LIST: "RELOAD_LIST",
    CHANGE_ALL_VALUE_FORM: "CHANGE_ALL_VALUE_FORM"
}

export default EmployeeActions;

