const ordersActions = {
    CHANGE_VALUE: "CHANGE_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_VALUE_FORM",
    RELOAD_LIST: "RELOAD_LIST",
    RESET_FORM: "RESET_FORM",
    CHANGE_ALL_VALUE_FORM: "CHANGE_ALL_VALUE_FORM",
    LOADED_ORDERS_LIST: "LOADED_ORDERS_LIST",
    ADD_MENU_ITEM: "ADD_MENU_ITEM",
    DELETE_MENU_ITEM: "DELETE_MENU_ITEM",
    CHANGE_FILTER: "CHANGE_FILTER"
}

export default ordersActions