const CustomerActions = {
    LOADING_CUSTOMERS_LIST: "LOADING_CUSTOMERS_LIST",
    LOADED_CUSTOMERS_LIST: "LOADED_CUSTOMERS_LIST",
    GET_CUSTOMERS_LIST: "GET_CUSTOMERS_LIST",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    CHANGE_VALUE: "CHANGE_CUSTOMER_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_CUSTOMER_FORM_VALUE",
    SET_SEARCH_TERM: "SET_CUSTOMERS_SEARCH_TERM",
    RESET_FORM: "RESET_CUSTOMER_FORM",
    SET_CURRENT_CUSTOMER: "SET_CURRENT_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER"
}

export default CustomerActions;