const CustomerActions = {
    LOADED_CUSTOMERS_LIST: "LOADED_CUSTOMERS_LIST",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    CHANGE_VALUE: "CHANGE_CUSTOMER_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_CUSTOMER_FORM_VALUE",
    SET_SEARCH_TERM: "SET_CUSTOMERS_SEARCH_TERM",
    CLEAN_FORM_DATA: "CLEAN_FORM_DATA",
    SET_CURRENT_CUSTOMER: "SET_CURRENT_CUSTOMER",
    RELOAD_LIST: "RELOAD_LIST",
    CHANGE_ALL_VALUE_FORM: "CHANGE_ALL_VALUE_FORM"
}

export default CustomerActions;

