const menuActions = {
    CHANGE_VALUE: "CHANGE_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_VALUE_FORM",
    RELOAD_LIST: "RELOAD_LIST",
    RESET_FORM: "RESET_FORM",
    CHANGE_ALL_VALUE_FORM: "CHANGE_ALL_VALUE_FORM",
    LOADED_MENU_LIST: "LOADED_MENU_LIST",
    ADD_IMAGES: "ADD_IMAGES",
    DELETE_IMAGE: "DELETE_IMAGE"
}

export default menuActions

